name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Force release type (leave empty for automatic)'
        required: false
        type: choice
        options:
          - auto
          - patch
          - minor
          - major

# Add permissions needed for semantic-release
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Check for vulnerabilities
        run: npm audit --production

  build-and-release:
    needs: verify
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build and Package Extension
        run: npm run package
      
      - name: Force Release Type
        if: github.event.inputs.release-type != ''
        run: |
          echo "RELEASE_TYPE=${{ github.event.inputs.release-type }}" >> $GITHUB_ENV
      
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
        run: npx semantic-release 