name: Verify Cross-Package Imports

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.8.0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Find cross-package imports
        run: pnpm run find:imports
      
      - name: Validate imports
        run: pnpm run validate:imports
      
      - name: Build packages
        run: pnpm run build
      
      - name: Run integration tests
        run: pnpm --filter @webcore/backend test 